# config/cable.yml

development:
  adapter: disabled
  # Disables Action Cable in development

test:
  adapter: test
  # Retain the test adapter if needed

production:
  adapter: disabled
  # Disables Action Cable in production

