default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sunny_development
  username: <%= ENV['PG_USERNAME'] %>  
  password: <%= ENV['PG_PASSWORD'] %> 
  host: localhost 

test:
  <<: *default
  database: sunny_test

# Production database configuration
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
